CREATE DATABASE "test_database_icu_rules_$%{}[]()&*^!@""""""""'`\/#"

    TEMPLATE = template0
    ENCODING = 'UTF8'
    ICU_LOCALE = 'und'
    ICU_RULES = '&V << w <<< W'
    LOCALE_PROVIDER = 'icu'
    IS_TEMPLATE = False;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE ALL ON SEQUENCES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
