-- Database: <TEST_DB_NAME>

-- DROP DATABASE IF EXISTS <TEST_DB_NAME>;

CREATE DATABASE <TEST_DB_NAME>
    WITH
    OWNER = <OWNER>
    ENCODING = 'UTF8'
    LC_COLLATE = '<LC_COLLATE>'
    LC_CTYPE = '<LC_CTYPE>'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE ALL ON TABLES FROM <OWNER>;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLES TO <OWNER>;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT DELETE, MAINTAIN, UPDATE ON TABLES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT SELECT, UPDATE ON SEQUENCES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT EXECUTE ON FUNCTIONS TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT USAGE ON TYPES TO test_default_priv_user;
