
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT EXECUTE ON FUNCTIONS TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT DELETE, MAINTAIN, UPDATE ON TABLES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT SELECT, UPDATE ON SEQUENCES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT USAGE ON TYPES TO test_default_priv_user;
