
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT EXECUTE ON FUNCTIONS TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT DELETE, MAINTAIN, UPDATE ON TABLES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT SELECT, UPDATE ON SEQUENCES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres
GRANT USAGE ON TYPES TO test_default_priv_user;
