{{- if and .Values.config_local.enabled (empty .Values.config_local.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgadmin4.fullname" . }}-config
  {{- with .Values.commonLabels }}
  labels: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations: {{ . | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.config_local.configKey }}: | {{ tpl .Values.config_local.data . | nindent 4 }}
{{- end }}