/////////////////////////////////////////////////////////////
//
// pgAdmin 4 - PostgreSQL Tools
//
// Copyright (C) 2013 - 2026, The pgAdmin Development Team
// This software is released under the PostgreSQL Licence
//
//////////////////////////////////////////////////////////////

import { useState } from 'react';
import PropTypes from 'prop-types';
import { Box } from '@mui/material';
import pgAdmin from 'sources/pgadmin';
import gettext from 'sources/gettext';
import url_for from 'sources/url_for';
import getApiInstance, { parseApiError } from '../../../../static/js/api_instance';
import { copyToClipboard } from '../../../../static/js/clipboard';
import { ModalContent, ModalFooter } from '../../../../static/js/components/ModalContent';
import { DefaultButton, PrimaryButton } from '../../../../static/js/components/Buttons';
import { InputText } from '../../../../static/js/components/FormComponents';

export function StarfleetPasswordContent({node, onClose}) {
  const password = node.starfleet_password;
  const hasPassword = typeof password === 'string' && password !== '';
  const canSave = hasPassword && Boolean(node.allow_save_password);
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const savePassword = ()=>{
    setSaving(true);
    setError('');
    getApiInstance().post(
      url_for('starfleet.save_password', {sid: node.sid}),
      {password: password}
    ).then(()=>{
      setSaved(true);
    }).catch((err)=>{
      setError(parseApiError(err));
    }).finally(()=>{
      setSaving(false);
    });
  };

  const copyPassword = async ()=>{
    setError('');
    try {
      await copyToClipboard(password);
    } catch (err) {
      setError(parseApiError(err));
    }
  };

  return (
    <ModalContent>
      <Box sx={{padding: '1rem', flexGrow: 1}}>
        <Box sx={{marginBottom: '0.75rem'}}>
          {hasPassword ?
            gettext('This password was generated by pgEdge Starfleet and will not be shown again in pgAdmin. Copy it now, or save it with the server.') :
            gettext('The database password is not available in pgAdmin, for example because the session was cleared before the deployment finished. You can reset it from the Starfleet console.')}
        </Box>
        <Box sx={{display: 'flex', gap: '0.5rem', marginBottom: '0.25rem'}}>
          <Box sx={{fontWeight: 'bold'}}>{gettext('Host')}</Box>
          <Box>{node.host}</Box>
        </Box>
        <Box sx={{display: 'flex', gap: '0.5rem', marginBottom: '0.75rem'}}>
          <Box sx={{fontWeight: 'bold'}}>{gettext('Username')}</Box>
          <Box>{node.username}</Box>
        </Box>
        {hasPassword &&
          <Box sx={{display: 'flex', gap: '0.5rem', alignItems: 'center'}}>
            <Box sx={{flexGrow: 1}}>
              <InputText aria-label={gettext('Password')} value={password} readonly={true} controlProps={{maxLength: 1024}}
                onChange={()=>{/* read-only */}} />
            </Box>
            <DefaultButton onClick={copyPassword}>{gettext('Copy')}</DefaultButton>
          </Box>
        }
        {saved && <Box sx={{marginTop: '0.75rem'}}>{gettext('The password has been saved with the server.')}</Box>}
        {error && <Box sx={{marginTop: '0.75rem', color: 'error.main'}}>{error}</Box>}
      </Box>
      <ModalFooter>
        {canSave &&
          <PrimaryButton onClick={savePassword} disabled={saving || saved}>{gettext('Save password')}</PrimaryButton>
        }
        <DefaultButton onClick={onClose}>{gettext('Close')}</DefaultButton>
      </ModalFooter>
    </ModalContent>
  );
}

StarfleetPasswordContent.propTypes = {
  node: PropTypes.shape({
    sid: PropTypes.number,
    host: PropTypes.string,
    username: PropTypes.string,
    starfleet_password: PropTypes.string,
    allow_save_password: PropTypes.bool,
  }).isRequired,
  onClose: PropTypes.func,
};

export function showStarfleetPassword(node) {
  pgAdmin.Browser.notifier.showModal(
    gettext('pgEdge Starfleet database password'),
    (onClose)=><StarfleetPasswordContent node={node} onClose={onClose} />,
    {
      isFullScreen: false,
      isResizeable: false,
      showFullScreen: false,
      isFullWidth: false,
      dialogWidth: 500,
      dialogHeight: 300,
      id: 'id-starfleet-password',
    }
  );
}
