-- Database: <TEST_DB_NAME>

-- DROP DATABASE IF EXISTS <TEST_DB_NAME>;

CREATE DATABASE <TEST_DB_NAME>
    WITH
    OWNER = <OWNER>
    ENCODING = 'UTF8'
    LC_COLLATE = '<LC_COLLATE>'
    LC_CTYPE = '<LC_CTYPE>'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE ALL ON TABLES FROM <OWNER>;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE ALL ON SEQUENCES FROM <OWNER>;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT SELECT, USAGE ON SEQUENCES TO PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE USAGE ON TYPES FROM PUBLIC;
