CREATE DATABASE "test_database_$%{}[]()&*^!@""""""""'`\/#"

    ENCODING = 'UTF8'
    IS_TEMPLATE = False;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE ALL ON SEQUENCES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> REVOKE USAGE ON TYPES FROM PUBLIC;
