CREATE DATABASE "test_database_icu_$%{}[]()&*^!@""""""""'`\/#"

    TEMPLATE = template0
    ENCODING = 'UTF8'
    ICU_LOCALE = 'en-US'
    LOCALE_PROVIDER = 'icu'
    IS_TEMPLATE = False;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE ALL ON SEQUENCES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
