[loggers]
keys=root, gunicorn

[handlers]
keys=console

[formatters]
keys=json

[logger_root]
level=INFO
handlers=console

[logger_gunicorn]
level=INFO
handlers=console
propagate=0
qualname=gunicorn

[handler_console]
class=StreamHandler
formatter=json
args=(sys.stdout, )

[formatter_json]
class=jsonformatter.JsonFormatter
format={"time": "asctime","message": "message","level": "levelname"}

