
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON FUNCTIONS FROM test_default_priv_user;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT EXECUTE ON FUNCTIONS TO test_default_priv_user WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON TABLES FROM test_default_priv_user;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON TABLES FROM test_default_priv_user;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT DELETE ON TABLES TO test_default_priv_user WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT TRUNCATE ON TABLES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON SEQUENCES FROM test_default_priv_user;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON SEQUENCES FROM test_default_priv_user;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT UPDATE ON SEQUENCES TO test_default_priv_user WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON TYPES FROM test_default_priv_user;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT USAGE ON TYPES TO test_default_priv_user WITH GRANT OPTION;
