

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
    REVOKE ALL ON SEQUENCES FROM <OWNER>;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER>
GRANT SELECT, USAGE ON SEQUENCES TO PUBLIC;
