
ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT EXECUTE ON FUNCTIONS TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT DELETE, MAINTAIN, UPDATE ON TABLES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT SELECT, UPDATE ON SEQUENCES TO test_default_priv_user;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT USAGE ON TYPES TO test_default_priv_user;
