CREATE DATABASE "test_database_builtin_$%{}[]()&*^!@""""""""'`\/#"

    TEMPLATE = template0
    ENCODING = 'UTF8'
    BUILTIN_LOCALE = 'C.UTF-8'
    LOCALE_PROVIDER = 'builtin'
    IS_TEMPLATE = False;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE ALL ON SEQUENCES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
