

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
    REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
    REVOKE ALL ON SEQUENCES FROM enterprisedb;
ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT USAGE, SELECT ON SEQUENCES TO PUBLIC;
