-- Database: <TEST_DB_NAME>

-- DROP DATABASE IF EXISTS <TEST_DB_NAME>;

CREATE DATABASE <TEST_DB_NAME>
    WITH
    OWNER = enterprisedb
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT TRUNCATE ON TABLES TO test_default_priv_user;
ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT DELETE ON TABLES TO test_default_priv_user WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT UPDATE ON SEQUENCES TO test_default_priv_user WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT EXECUTE ON FUNCTIONS TO test_default_priv_user WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT USAGE ON TYPES TO test_default_priv_user WITH GRANT OPTION;
