

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
    REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
    REVOKE ALL ON SEQUENCES FROM enterprisedb;
ALTER DEFAULT PRIVILEGES FOR ROLE enterprisedb
GRANT SELECT, USAGE ON SEQUENCES TO PUBLIC;
