/* eslint-env node */

module.exports  = {
  name: 'nodes',
  isReference: true,
  createSourceMap: true,
  dependencies: ['vendor', 'codemirror', 'core'],
  entry: [
    'pgadmin.node.language', 'pgadmin.node.mview', 'pgadmin.node.pga_jobstep',
    'pgadmin.node.foreign_server', 'pgadmin.node.domain', 'pgadmin.node.role',
    'pgadmin.node.constraints', 'pgadmin.browser.table.partition.utils',
    'pgadmin.node.catalog', 'pgadmin.node.check_constraint',
    'pgadmin.node.user_mapping', 'pgadmin.node.collation', 'pgadmin.node.rule',
    'pgadmin.node.tablespace', 'pgadmin.node.server', 'pgadmin.node.package',
    'pgadmin.node.table', 'pgadmin.node.server_group',
    'pgadmin.node.fts_configuration', 'pgadmin.node.event_trigger',
    'pgadmin.node.pga_job', 'pgadmin.node.function', 'pgadmin.node.edbfunc',
    'pgadmin.node.sequence', 'pgadmin.node.edbproc', 'pgadmin.node.procedure',
    'pgadmin.node.domain_constraints', 'pgadmin.node.catalog_object',
    'pgadmin.node.foreign_data_wrapper', 'pgadmin.node.foreign_key',
    'pgadmin.node.resource_group', 'pgadmin.node.exclusion_constraint',
    'pgadmin.node.primary_key', 'pgadmin.node.schema', 'pgadmin.node.view',
    'pgadmin.node.pga_schedule', 'pgadmin.node.catalog_object_column',
    'pgadmin.node.synonym', 'pgadmin.node.extension', 'pgadmin.node.database',
    'pgadmin.node.unique_constraint', 'pgadmin.node.partition',
    'pgadmin.node.trigger', 'pgadmin.node.edbvar', 'pgadmin.node.fts_template',
    'pgadmin.node.cast', 'pgadmin.node.fts_parser', 'pgadmin.node.column',
    'pgadmin.node.foreign_table', 'pgadmin.node.fts_dictionary',
    'pgadmin.node.trigger_function', 'pgadmin.node.index', 'pgadmin.node.type',
  ],
  shimConfig: {
    shim: {},
    alias: {
      'pgadmin.node.language': 'pgadmin/browser/server_groups/servers/databases/languages/static/js/language',
      'pgadmin.node.mview': 'pgadmin/browser/server_groups/servers/databases/schemas/views/static/js/mview',
      'pgadmin.node.pga_jobstep': 'pgadmin/browser/server_groups/servers/pgagent/steps/static/js/pga_jobstep',
      'pgadmin.node.foreign_server': 'pgadmin/browser/server_groups/servers/databases/foreign_data_wrappers/foreign_servers/static/js/foreign_server',
      'pgadmin.node.domain': 'pgadmin/browser/server_groups/servers/databases/schemas/domains/static/js/domain',
      'pgadmin.node.constraints': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/constraints/static/js/constraints',
      'pgadmin.browser.table.partition.utils': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/static/js/partition.utils',
      'pgadmin.node.catalog': 'pgadmin/browser/server_groups/servers/databases/schemas/static/js/catalog',
      'pgadmin.node.role': 'pgadmin/browser/server_groups/servers/roles/static/js/role',
      'pgadmin.node.check_constraint': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/constraints/check_constraint/static/js/check_constraint',
      'pgadmin.node.user_mapping': 'pgadmin/browser/server_groups/servers/databases/foreign_data_wrappers/foreign_servers/user_mapping/static/js/user_mapping',
      'pgadmin.node.collation': 'pgadmin/browser/server_groups/servers/databases/schemas/collations/static/js/collation',
      'pgadmin.node.table': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/static/js/table',
      'pgadmin.node.tablespace': 'pgadmin/browser/server_groups/servers/tablespaces/static/js/tablespace',
      'pgadmin.node.server': 'pgadmin/browser/server_groups/servers/static/js/server',
      'pgadmin.node.package': 'pgadmin/browser/server_groups/servers/databases/schemas/packages/static/js/package',
      'pgadmin.node.rule': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/rules/static/js/rule',
      'pgadmin.node.server_group': 'pgadmin/browser/server_groups/static/js/server_group',
      'pgadmin.node.fts_configuration': 'pgadmin/browser/server_groups/servers/databases/schemas/fts_configurations/static/js/fts_configuration',
      'pgadmin.node.event_trigger': 'pgadmin/browser/server_groups/servers/databases/event_triggers/static/js/event_trigger',
      'pgadmin.node.pga_job': 'pgadmin/browser/server_groups/servers/pgagent/static/js/pga_job',
      'pgadmin.node.function': 'pgadmin/browser/server_groups/servers/databases/schemas/functions/static/js/function',
      'pgadmin.node.edbfunc': 'pgadmin/browser/server_groups/servers/databases/schemas/packages/edbfuncs/static/js/edbfunc',
      'pgadmin.node.sequence': 'pgadmin/browser/server_groups/servers/databases/schemas/sequences/static/js/sequence',
      'pgadmin.node.edbproc': 'pgadmin/browser/server_groups/servers/databases/schemas/packages/edbfuncs/static/js/edbproc',
      'pgadmin.node.domain_constraints': 'pgadmin/browser/server_groups/servers/databases/schemas/domains/domain_constraints/static/js/domain_constraints',
      'pgadmin.node.catalog_object': 'pgadmin/browser/server_groups/servers/databases/schemas/catalog_objects/static/js/catalog_object',
      'pgadmin.node.foreign_data_wrapper': 'pgadmin/browser/server_groups/servers/databases/foreign_data_wrappers/static/js/foreign_data_wrapper',
      'pgadmin.node.foreign_key': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/constraints/foreign_key/static/js/foreign_key',
      'pgadmin.node.procedure': 'pgadmin/browser/server_groups/servers/databases/schemas/functions/static/js/procedure',
      'pgadmin.node.resource_group': 'pgadmin/browser/server_groups/servers/resource_groups/static/js/resource_group',
      'pgadmin.node.exclusion_constraint': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/constraints/exclusion_constraint/static/js/exclusion_constraint',
      'pgadmin.node.primary_key': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/constraints/index_constraint/static/js/primary_key',
      'pgadmin.node.schema': 'pgadmin/browser/server_groups/servers/databases/schemas/static/js/schema',
      'pgadmin.node.view': 'pgadmin/browser/server_groups/servers/databases/schemas/views/static/js/view',
      'pgadmin.node.pga_schedule': 'pgadmin/browser/server_groups/servers/pgagent/schedules/static/js/pga_schedule',
      'pgadmin.node.catalog_object_column': 'pgadmin/browser/server_groups/servers/databases/schemas/catalog_objects/columns/static/js/catalog_object_column',
      'pgadmin.node.synonym': 'pgadmin/browser/server_groups/servers/databases/schemas/synonyms/static/js/synonym',
      'pgadmin.node.extension': 'pgadmin/browser/server_groups/servers/databases/extensions/static/js/extension',
      'pgadmin.node.unique_constraint': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/constraints/index_constraint/static/js/unique_constraint',
      'pgadmin.node.database': 'pgadmin/browser/server_groups/servers/databases/static/js/database',
      'pgadmin.node.edbvar': 'pgadmin/browser/server_groups/servers/databases/schemas/packages/edbvars/static/js/edbvar',
      'pgadmin.node.trigger': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/triggers/static/js/trigger',
      'pgadmin.node.partition': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/partitions/static/js/partition',
      'pgadmin.node.fts_template': 'pgadmin/browser/server_groups/servers/databases/schemas/fts_templates/static/js/fts_template',
      'pgadmin.node.cast': 'pgadmin/browser/server_groups/servers/databases/casts/static/js/cast',
      'pgadmin.node.fts_parser': 'pgadmin/browser/server_groups/servers/databases/schemas/fts_parser/static/js/fts_parser',
      'pgadmin.node.column': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/column/static/js/column',
      'pgadmin.node.foreign_table': 'pgadmin/browser/server_groups/servers/databases/schemas/foreign_tables/static/js/foreign_table',
      'pgadmin.node.fts_dictionary': 'pgadmin/browser/server_groups/servers/databases/schemas/fts_dictionaries/static/js/fts_dictionary',
      'pgadmin.node.trigger_function': 'pgadmin/browser/server_groups/servers/databases/schemas/functions/static/js/trigger_function',
      'pgadmin.node.index': 'pgadmin/browser/server_groups/servers/databases/schemas/tables/indexes/static/js/index',
      'pgadmin.node.type': 'pgadmin/browser/server_groups/servers/databases/schemas/types/static/js/type',
    }
  }
};
