REVOKE ALL ON SCHEMA "test_schema_$%{}[]()&*^!@""""'`\/#" FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> IN SCHEMA "test_schema_$%{}[]()&*^!@""""'`\/#"
    REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE <OWNER> IN SCHEMA "test_schema_$%{}[]()&*^!@""""'`\/#"
    REVOKE ALL ON TYPES FROM PUBLIC;
