SELECT (PG_CATALOG.CONCAT(PG_CATALOG.QUOTE_IDENT(nspc.nspname),'.',PG_CATALOG.QUOTE_IDENT(PGCOL.COLLNAME))) AS collationame
		FROM PG_PARTITIONED_TABLE PARTT
		LEFT OUTER JOIN PG_CATALOG.PG_COLLATION PGCOL
				ON PGCOL.OID = 950
		LEFT OUTER JOIN PG_CATALOG.PG_NAMESPACE NSPC
				ON PGCOL.COLLNAMESPACE = NSPC.OID
	WHERE PARTRELID = 162140
